version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "8000:8000"
      - "9090:9090"
    volumes:
      - model-data:/app/models
    environment:
      - API_KEY=${API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - WHISPER_THREADS=4
      - TTS_THREADS=4
      - OLLAMA_MODEL=mixtral-optimized
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  model-data:
